caprino/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('caprino.core.urls')),
    path('animais/', include('caprino.animais.urls')),
    path('relatorios/', include('caprino.relatorios.urls')),
    path('rede/', include('caprino.rede.urls')),
    path('contas/', include('caprino.contas.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

caprino/animais/forms.py
from django import forms
from . import models

class CreateAnimais(forms.ModelForm):

    rgb_animal = forms.CharField(required=False, label='RGB', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'RGB do Animal'}))
    nome_animal = forms.CharField(required=False, label='Nome', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Animal'}))
    numero_animal = forms.IntegerField(required=False, label='Numero', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número do Animal'}))
    sexo_animal = forms.ModelChoiceField(required=True, label='Sexo', queryset=models.Sexo.objects.all(), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    nascimento_animal = forms.DateField(required=True, label='Nascimento', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Nascimento do Animal', 'type': 'date'}))
    raca_animal = forms.ModelChoiceField(required=True, label='Raça', queryset=models.Raca.objects.all(), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    sangue_animal = forms.ModelChoiceField(required=True, label='Sangue', queryset=models.Sangue.objects.all(), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    brincos_animal = forms.CharField(required=True, label='Brincos', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Brincos'}))
    vida_animal = forms.ModelChoiceField(required=True, label='Vida', queryset=models.Vida.objects.all(), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    mae_animal = forms.ModelChoiceField(required=False, label='Mãe', queryset=models.Animal.objects.all().filter(sexo_animal=2).filter(vida_animal=2), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    pai_animal = forms.ModelChoiceField(required=False, label='Pai', queryset=models.Animal.objects.all().filter(sexo_animal=1).filter(vida_animal=2), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    observacao_animal = forms.CharField(required=False, label='Observação', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Observação'}))
    foto_animal = forms.ImageField(required=False, label='Foto do animal')

    class Meta():
        model = models.Animal 
        fields = '__all__'


class CreateCoberturas(forms.ModelForm):

    inicio_cobertura = forms.DateField(required=True, label='Inicio', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Início de Cobertura', 'type': 'date'}))
    fim_cobertura = forms.DateField(required=True, label='Fim', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Fim de Cobertura', 'type': 'date'}))
    id_cabra = forms.ModelMultipleChoiceField(required=True, label='Cabra', queryset=models.Animal.objects.all(
    ).filter(sexo_animal=2).filter(vida_animal=2), to_field_name='id', widget=forms.SelectMultiple(attrs={'class': 'js-example-basic-multiple form-control'}))
    id_bode = forms.ModelChoiceField(required=True, label='Bode', queryset=models.Animal.objects.all().filter(sexo_animal=1).filter(vida_animal=2), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta():
        model = models.Cobertura
        fields = '__all__'

    def save(self):
        data = self.cleaned_data
        cobertura = models.Cobertura(
            id_bode=data['id_bode'], inicio_cobertura=data['inicio_cobertura'], fim_cobertura=data['fim_cobertura'])
        cobertura.save()

        self.save_related_objects(cobertura)

    def save_related_objects(self, cobertura):
        cabras = self.cleaned_data.pop('id_cabra', {})

        for cabra in cabras:
            status_cobertura = models.StatusCobertura(
                id_cobertura=cobertura, id_cabra=cabra)
            status_cobertura.save()
        

class CreateProducao(forms.ModelForm):

    data_producao = forms.DateField(required=True, label='Data', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Data de Produção', 'type': 'date'}))
    manha_producao = forms.CharField(required=True, label='Peso Manhã', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Peso Manhã'}))
    tarde_producao = forms.CharField(required=True, label='Peso Tarde', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Peso Tarde'}))
          

    class Meta():
        model = models.Producao
        fields = ['data_producao', 'manha_producao', 'tarde_producao', 'id_cabra', 'descarte_producao']


class CreateMedicacao(forms.ModelForm):

    id_animal = forms.ModelChoiceField(required=True, label='Animal', queryset=models.Animal.objects.all().filter(vida_animal=2), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    medicacao = forms.ModelChoiceField(required=True, label='Medicação', queryset=models.TipoMedicacao.objects.all(), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    data_medicacao = forms.DateField(required=True, label='Data de Aplicação', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Data de Aplicação', 'type': 'date'}))
    observacao_medicacao = forms.CharField(required=False, label='Observação', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Observação'}))
    inicio_carencia = forms.DateField(required=False, label='Início Carência', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Início Carência', 'type': 'date'}))
    fim_carencia = forms.DateField(required=False, label='Fim Carência', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Fim Carência', 'type': 'date'}))

    class Meta():
        model = models.Medicacao  
        fields = '__all__'  

class CreateParto(forms.ModelForm):

    data_parto = forms.DateField(required=True, label='Data de Parto', widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Data de Parto', 'type': 'date'}))
    parto = forms.ModelChoiceField(required=True, label='Tipo', queryset=models.TipoParto.objects.all(), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))
    vivos_parto = forms.IntegerField(required=False, label='Vivos', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Vivos'}))
    observacao_parto = forms.CharField(required=False, label='Observação', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Observação'}))
    id_cabra = forms.ModelChoiceField(required=True, label='Animal', queryset=models.Animal.objects.all().filter(vida_animal=2).filter(sexo_animal=2), empty_label='Selecione uma opção', to_field_name='id', widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta():
        model = models.Parto  
        fields = '__all__' 

templates/producao/createProducao.html
{% extends 'base.html' %}
<!-- usando base.html como base -->
{% block conteudo %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
    <div class=" container-fluid  ">
        <a class="navbar-brand" href="#pablo"> Cadastro de Produção </a>
        <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-toggle="dropdown">
                        <span class="d-lg-none">Cadastro de Produção</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caprino.contas:Sair' %}">
                        <span class="no-icon">SAIR</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {#  Mensagens de erro  #}
                <div id="alerts" class="alert alert-dismissible fade show" role="alert" hidden></div>
                {% if messages %}
                    {% for message in messages %}
                        <div id="alerts_div" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>   
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Cadastro de Produção</h4>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{% url 'caprino.animais:Nova_Producao' pk=cabra.id %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label>Data</label><span style="color: red">*</span>
                                        <i data-toggle="tooltip" title="" class="fa fa-info-circle" aria-hidden="true" data-original-title="Selecione a data da pesagem do leite"></i>
                                        {{ producao_form.data_producao }}
                                        <input type="hidden" name="id_cabra" id="id_cabra" value="{{ cabra.id }}">
                                        <!-- <input type="text" class="form-control" disabled="" placeholder="Company" value="Creative Code Inc."> -->
                                    </div>
                                </div>
                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label>Descarte</label>
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input class="form-check-input" type="checkbox" name="descarte_producao" value="1">
                                                <span class="form-check-sign"></span>
                                            </label>
                                        </div> 
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label>Peso Manhã</label><span style="color: red">*</span>
                                        <i data-toggle="tooltip" title="" class="fa fa-info-circle" aria-hidden="true" data-original-title="Digite a pesagem do leite separada por '.' Exemplo: 1.2"></i>
                                        {{ producao_form.manha_producao }}
                                        <!-- <input type="text" class="form-control" placeholder="Username" value="michael23"> -->
                                    </div>
                                </div>

                                <div class="col-md-4 pr-1">
                                    <div class="form-group">
                                        <label>Peso tarde</label><span style="color: red">*</span>
                                        <i data-toggle="tooltip" title="" class="fa fa-info-circle" aria-hidden="true" data-original-title="Digite a pesagem do leite separada por '.' Exemplo: 1.2"></i>
                                        {{ producao_form.tarde_producao }}
                                        <!-- <input type="text" class="form-control" disabled="" placeholder="Company" value="Creative Code Inc."> -->
                                    </div>
                                </div>
                            </div>
                             {% comment %} {{ producao_form.id_cabra }} {% endcomment %}
                            
                            <button type="submit" class="btn btn-info btn-fill pull-right">Salvar</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#id_data_producao').change(function (){
                const data_producao = $(this).val();
                const id_cabra = $('#id_cabra').val(); 

                $.get(`/animais/verifica_periodo_carencia/${id_cabra}/${data_producao}`, 
                function (data) {
                    if (data.ok === false) {
                        $('#alerts').html(data.msg);
                        $('#alerts').addClass('alert-danger');
                        $('#alerts').attr('hidden', false);
                    }
                })
            })
        });
    </script>
{% endblock %}

templates/producao/descarte.html
{% extends 'base.html' %}
<!-- usando base.html como base -->
{% block conteudo %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
    <div class=" container-fluid  ">
        <a class="navbar-brand" href="#pablo"> Relatórios </a>
        <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-toggle="dropdown">
                        <span class="d-lg-none">Relatórios</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caprino.contas:Sair' %}">
                        <span class="no-icon">SAIR</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

<div class="content">
    <div class="container-fluid">
        <!-- <div class="row">
            <div class="col-md-9">
                <div class="card ">
                    <div class="card-header ">
                        <h4 class="card-title">Relatório Descarte Produção Leiteira</h4>
                    </div>
                    <div class="card-body ">
                        <canvas id="myChart"></canvas>
                    </div>
                    <div class="card-footer ">
                        <hr>
                        <div style="float: right;">
                            <i class="fa fa-clock-o"></i> Produção Total: {{ soma }}
                        </div>
                    </div>
                </div>
            </div>
        </div> -->
        <div class="row">
                <div class="col-md-12">
                    <div class="card strpied-tabled-with-hover">
                        <div class="card-header ">
                            <h4 class="card-title">Descartes</h4>
                            {% comment %}
                            <p class="card-category">Here is a subtitle for this table</p> {% endcomment %}
                        </div>
                        <div class="card-body table-full-width table-responsive">
                            <table class="table table-hover table-striped">
                                <thead>  
                                    <tr>
                                        <th>Cabra</th>
                                        <th>Data</th>
                                        <th>Descarte Manhã</th>
                                        <th>Descarte tarde</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for p in producao %}
                                    <tr>
                                        <td>{{ p.brincos_animal }}</td>
                                        <td>{{ p.data_producao }}</td>
                                        <td>{{ p.manha_producao }}</td> 
                                        <td>{{ p.tarde_producao }}</td> 
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %} {% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var grafico = JSON.parse('{{ grafico|safe }}');

    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',
        // The data for our dataset
        data: {
            labels: grafico.data_prod,
            datasets: [{
                label: "Curva Produção",
                backgroundColor: 'rgb(255,165,0)',
                borderColor: 'rgb(255,140,0)',
                data: grafico.manha_prod,
            }]
        },
        // Configuration options go here
        options: {
				responsive: true,
				
				tooltips: {
					mode: 'index',
					intersect: false,
				},
				hover: {
					mode: 'nearest',
					intersect: true
				},
				scales: {
					xAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Dias do mês'
						}
					}],
					yAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: 'Produção (em kg)'
						}
					}]
				}
			}
    });

    
</script> {% endblock %}

templates/producao/listaCabras.html
{% extends 'base.html' %}
<!-- usando base.html como base -->
{% block conteudo %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
    <div class=" container-fluid  ">
        <a class="navbar-brand" href="#pablo">Cabras </a>
        <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-toggle="dropdown">
                        <span class="d-lg-none">Cabras</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caprino.contas:Sair' %}">
                        <span class="no-icon">SAIR</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {#  Mensagens de erro  #}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>   
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card strpied-tabled-with-hover">
                    <div class="card-header ">
                        <h4 class="card-title">Cabras</h4>
                        {% comment %}
                        <p class="card-category">Here is a subtitle for this table</p> {% endcomment %}
                    </div>
                    <div class="card-body table-full-width table-responsive">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Brincos</th>
                                    {% comment %} <th>Raça</th> {% endcomment %}
                                </tr>
                            </thead>
                            <tbody>
                                {% for animal in animais %}
                                <tr>
                                    <td>{{ animal.brincos_animal }}</td>
                                    <td><a class="btn btn-success btn-fill btn-wd" href="{% url 'caprino.animais:Mostra_Producao' animal.id %}" title="Nova Produção">Nova Produção</a></td>
                                    {% comment %} <td>{{ animal.raca_animal }}</td> {% endcomment %}

                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        {% if animais.has_other_pages %}
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if animais.has_previous %}
                                    <li class="page-link"><a href="?page={{ animais.previous_page_number }}">&laquo;</a></li>
                                {% else %}
                                    <li class="page-link disabled"><span>&laquo;</span></li>
                                {% endif %}
                                {% for i in animais.paginator.page_range %}
                                    {% if animais.number == i %}
                                        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if animais.has_next %}
                                    <li class="page-link"><a href="?page={{ animais.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                    <li class="page-link disabled"><span>&raquo;</span></li>
                                {% endif %}
                            </ul>
                        </nav>
                        {% endif %}

                        {% comment %} <a style="float:right;" class="btn btn-success" href="{% url 'caprino.animais:Novo_Animal' %}" role="button">Novo Animal</a> {% endcomment %}

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/producao/mostraProducao.html
{% extends 'base.html' %}
<!-- usando base.html como base -->
{% block conteudo %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
    <div class=" container-fluid  ">
        <a class="navbar-brand" href="#pablo">Produção </a>
        <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link" data-toggle="dropdown">
                        <span class="d-lg-none">Produção</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'caprino.contas:Sair' %}">
                        <span class="no-icon">SAIR</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {#  Mensagens de erro  #}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>   
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card strpied-tabled-with-hover">
                    <div class="card-header ">
                        <h4 class="card-title">Produções Cadastradas</h4>
                        {% comment %}
                        <p class="card-category">Here is a subtitle for this table</p> {% endcomment %}
                    </div>
                    <div class="card-body table-full-width table-responsive">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Data</th>
                                    <th>Produção Manhã</th>
                                    <th>Produção tarde</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for p in producao %}
                                <tr>
                                    <td>{{ p.data_producao }}</td>
                                    <td>{{ p.manha_producao }}</td>
                                    <td>{{ p.tarde_producao }}</td>
                                    {% comment %} <td>{{ cabra }}</td> {% endcomment %}
                                    <td><a class="btn btn-primary btn-fill btn-wd" href="{% url 'caprino.animais:Atualiza_Producao' id_prod=p.id id_cabra=cabra %}" title="Editar">Editar</a></td>
                                    <td><a class="btn btn-danger btn-fill btn-wd" href="{% url 'caprino.animais:Delete_Producao' p.id %}" title="Apagar">Apagar</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        {% if producao.has_other_pages %}
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if producao.has_previous %}
                                    <li class="page-link"><a href="?page={{ producao.previous_page_number }}">&laquo;</a></li>
                                {% else %}
                                    <li class="page-link disabled"><span>&laquo;</span></li>
                                {% endif %}
                                {% for i in producao.paginator.page_range %}
                                    {% if producao.number == i %}
                                        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if producao.has_next %}
                                    <li class="page-link"><a href="?page={{ producao.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                    <li class="page-link disabled"><span>&raquo;</span></li>
                                {% endif %}
                            </ul>
                        </nav>
                        {% endif %}

                        <a style="float:right;" class="btn btn-success btn-fill btn-wd" href="{% url 'caprino.animais:Nova_Producao' cabra %}" role="button">Nova Producao</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}